config/routes.rb
Gene::Application.routes.draw do
  get "reproduction/mate"
  resources :organisms
  get "static_pages/gene"
  root :to => 'static_pages#gene'
  

end

app/models/organism.rb
class Organism < ActiveRecord::Base
end

app/models/reproduce.rb
class Reproduce
	def self.mate org1, org2
		organism_one = Organism.find(org1)
		organism_two = Organism.find(org2)
		organism_one.name + " " + organism_two.name
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/gene_controller.rb
class GeneController < ApplicationController
  def index
  end
end

app/controllers/mating_controller.rb
class MatingController < ApplicationController
  def index
    @organism = Organism.new
  end
  
  def mate
  end
end

app/controllers/organisms_controller.rb
class OrganismsController < ApplicationController
  # GET /organisms
  # GET /organisms.json
  def index
    @organisms = Organism.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @organisms }
    end
  end

  # GET /organisms/1
  # GET /organisms/1.json
  def show
    @organism = Organism.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @organism }
    end
  end

  # GET /organisms/new
  # GET /organisms/new.json
  def new
    @organism = Organism.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @organism }
    end
  end

  # GET /organisms/1/edit
  def edit
    @organism = Organism.find(params[:id])
  end

  # POST /organisms
  # POST /organisms.json
  def create
    @organism = Organism.new(params[:organism])

    respond_to do |format|
      if @organism.save
        format.html { redirect_to @organism, notice: 'Organism was successfully created.' }
        format.json { render json: @organism, status: :created, location: @organism }
      else
        format.html { render action: "new" }
        format.json { render json: @organism.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /organisms/1
  # PUT /organisms/1.json
  def update
    @organism = Organism.find(params[:id])

    respond_to do |format|
      if @organism.update_attributes(params[:organism])
        format.html { redirect_to @organism, notice: 'Organism was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @organism.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /organisms/1
  # DELETE /organisms/1.json
  def destroy
    @organism = Organism.find(params[:id])
    @organism.destroy

    respond_to do |format|
      format.html { redirect_to organisms_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/reproduction_controller.rb
class ReproductionController < ApplicationController
  def mate
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def gene
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gene_helper.rb
module GeneHelper
end

app/helpers/mating_helper.rb
module MatingHelper
end

app/helpers/organisms_helper.rb
module OrganismsHelper
  def mate(male,female)
    # if repro coefficients are in range, create a new organism
    if(female.repro_coefficient - male.repro_coefficient <= 0 )
    	
    end
  end
end

app/helpers/reproduction_helper.rb
module ReproductionHelper
end

app/helpers/static_pages_helper.rb
# Organism - species_name, longevity, repro_coefficient, name

module StaticPagesHelper
  def gen_dna_child(dna_m,dna_f,crossover_indexes)
	# add to crossover indexes
	crossover_indexes = crossover_indexes << dna_m.length 
	start = 0 # start index of dna
	cur_parent = (Random.rand() * 2).ceil == 1 ? "m":"f"  # initial splice 
	new_dna=''
  
	# For each crossover compute segment
	crossover_indexes.each do |cr|
	  if cur_parent == 'm'
		dna = dna_m
		cur_parent = 'f'
	  else
		dna = dna_f
		cur_parent = 'm'
	  end
	  new_dna += dna[start..cr-1] 
	  start=cr
	end
	new_dna
  end
end

app/views/gene/index.html.erb
<h1>Crossover Genetic Algorithm</h1>
<div>

<% 
dna_m = "qpwoeirzzxcvlkjhasdfertyhkjlcnbv"
dna_f = "qoiuykjhgnmbvafsdrtuykhjgnvbcbvj"
crossover_indexes = [8, 12, 18]
%>


<p>Parent Male Gene: <%= dna_m %></p>
<p>Parent Female Gene: <%= dna_f %></p>

<p>Child Gene: <%= gen_dna_child(dna_m,dna_f,crossover_indexes) %></p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Gene</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/mating/index.html.erb
<h1>Mating organisms</h1>

<%= form_for @organism, :url => mate_path, :method => :post do |f| %>
  <%=select("organism", "id", Organism.all.collect {|p| [ p.name, p.id ] }, {:include_blank => 'None'})%>
  <%=select("organism", "id", Organism.all.collect {|p| [ p.name, p.id ] }, {:include_blank => 'None'})%>

  <%= f.submit("Mate!") %>
<% end %>

app/views/organisms/_form.html.erb
<%= form_for(@organism) do |f| %>
  <% if @organism.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@organism.errors.count, "error") %> prohibited this organism from being saved:</h2>

      <ul>
      <% @organism.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :species %><br />
    <%= f.text_field :species %>
  </div>
  <div class="field">
    <%= f.label :longevity %><br />
    <%= f.number_field :longevity %>
  </div>
  <div class="field">
    <%= f.label :repro_coefficient %><br />
    <%= f.number_field :repro_coefficient %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :sex %><br />
    <%= f.text_field :sex %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/organisms/edit.html.erb
<h1>Editing organism</h1>

<%= render 'form' %>

<%= link_to 'Show', @organism %> |
<%= link_to 'Back', organisms_path %>

app/views/organisms/index.html.erb
<h1>Listing organisms</h1>

<table>
  <tr>
    <th>Species</th>
    <th>Longevity</th>
    <th>Repro coefficient</th>
    <th>Name</th>
    <th>Sex</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @organisms.each do |organism| %>
  <tr>
    <td><%= organism.species %></td>
    <td><%= organism.longevity %></td>
    <td><%= organism.repro_coefficient %></td>
    <td><%= organism.name %></td>
    <td><%= organism.sex %></td>
    <td><%= link_to 'Show', organism %></td>
    <td><%= link_to 'Edit', edit_organism_path(organism) %></td>
    <td><%= link_to 'Destroy', organism, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Organism', new_organism_path %>

app/views/organisms/new.html.erb
<h1>New organism</h1>

<%= render 'form' %>

<%= link_to 'Back', organisms_path %>

app/views/organisms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Species:</b>
  <%= @organism.species %>
</p>

<p>
  <b>Longevity:</b>
  <%= @organism.longevity %>
</p>

<p>
  <b>Repro coefficient:</b>
  <%= @organism.repro_coefficient %>
</p>

<p>
  <b>Name:</b>
  <%= @organism.name %>
</p>

<p>
  <b>Sex:</b>
  <%= @organism.sex %>
</p>

<%= link_to 'Edit', edit_organism_path(@organism) %> |
<%= link_to 'Back', organisms_path %>

app/views/reproduction/mate.html.erb
<h1>Mating organisms</h1>
<%= form_tag(reproduction_mate_path, :method => "post") do %>
  <%=select("organism", "organism_id", Organism.all.collect {|p| [ p.name, p.id ] }, {:include_blank => 'None'})%>
  <%=select("organism", "organism_id", Organism.all.collect {|p| [ p.name, p.id ] }, {:include_blank => 'None'})%>


  <%= submit_tag("Mate!") %>
<% end %>

<%=button_tag(:type => 'button',:disable_with => "Please wait...") do
  content_tag(:strong, 'Mate!')
end 
%>

app/views/static_pages/gene.html.erb
<h1>Crossover Genetic Algorithm</h1>
<div>

<% 
dna_m = "qpwoeirzzxcvlkjhasdfertyhkjlcnbv"
dna_f = "qoiuykjhgnmbvafsdrtuykhjgnvbcbvj"
crossover_indexes = [8, 12, 18]
%>


<p>Parent Male Gene: <%= dna_m %></p>
<p>Parent Female Gene: <%= dna_f %></p>

<p>Child Gene: <%=
gen_dna_child(dna_m,dna_f,crossover_indexes) %></p>
</div>

<p>test</p>

app/views/static_pages/home.html.erb
<h1>Genetics with Rails</h1>